homework 13
EasyCode-JavaScriptReact-v1/javascript-react-course-codewhynot pull request #11
Opened 2018-07-12 19:32 UTC by codewhynot

2018-07-13 05:02 UTC, OlegLustenko requested changes

2018-07-13 05:02 UTC, OlegLustenko commented on js-core/homeworks/homework-13/src/main.js
> +    constuctor () {}
constuctor -> conductor -> constructor :)

It's not really necessary to create a constructor

2020-11-01 10:36 UTC, closed without merging

2020-11-01 10:37 UTC, codewhynot commented
Close

2020-11-01 10:37 UTC, codewhynot commented
Close